apiVersion: apps/v1
kind: Deployment
metadata:
  name: produto-api-deployment
spec:
  replicas: 5
  selector:    
    matchLabels:
      app: produto-api      
  template:
    metadata:      
      labels:
        app: produto-api                
    spec:
      containers:
      - name: api
        image: kubedevio/api-produto:v1        
        resources: {}              
        ports:
        - containerPort: 8080
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongo-service:27017/admin

